# Generated by Django 5.1.6 on 2025-03-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_draft', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='wiki/')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolioapi.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=64000)),
                ('position', models.IntegerField()),
                ('is_editing', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='section/')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapi.wiki')),
            ],
        ),
    ]
